version: 0.1

phases:
  install:
    commands:
      - apt-get update -y 
      - npm install -g gulp-cli
  build:
    commands:
      - npm install && gulp build
  post_build:
    commands:
      - aws cloudformation package --template-file sam-template.json --output-template-file sam-output.yml --s3-bucket lambda-python-pipeline 
artifacts:
  type: zip
  files:
    - sam-output.yml
